### ISSUE TITLE
Drop categorical metadata with only one group before attempting to do Kruskal Wallis test

### ISSUE THREAD

**Issue by fwzhao** [epigen/spilterlize_integrate#13]
https://github.com/epigen/spilterlize_integrate/blob/964c4c01d956d42c519069c5431771feff96dd6d/workflow/scripts/plot_diagnostics.R#L165C1-L171C7

Otherwise there's an error since you can't with only one group. Perhaps worth dropping earlier.

**Comment by fwzhao** [comment]
Ah - just to elaborate, there is a section of code already to drop non-varying metadata (line 133)... but this does not filter out metadata where NAs are involved, which then draws an error by Kruskal-Wallis

I.e. For a metadata column with "TRUE" and "<NA>" as factor levels
(1) Line 133 - annot <- annot[, apply(annot, 2, function(x) length(unique(x)) > 1)] does not filter these out since it has more than one unique factor level
(2) When KW test is run, I suppose the <NA> factor level is dropped... and suddenly there is only one factor_level for this column... and voila: Error! :)

**Comment by sreichl** [comment]
thanks for the clarification and details. the more the better. this will accelerate the resolution of this issue.
