### ISSUE TITLE
How to run in parallel on multiple input data files?

### ISSUE THREAD

**Issue by bednarsky** [epigen/spilterlize_integrate#16]
Hi Stephan!

I have multiple cell type levels (e.g., more and more finegrained). I would like to do the whole DEA recipe on each level separately, in parallel. For [dea_limma](https://github.com/epigen/dea_limma) I can just do this by setting the paths in the annotation file to match the wildcards for the different levels. For `spilterlize_integrate`, however, there is only a single `data` file as input. What's the best way to do this in parallel? 

I thought about just using the module 4 times, for each of my cell type levels, potentially in a loop making the rules? 

Thanks!

Edit: This is how I do it for a single cell type level
```snakemake
ct_level = 'L2'
config_wf['ct_annotated_spilterlize_integrate']['data'] = res_path_dea / 'pseudobulks' / f'{ct_level}__raw_counts.csv'
config_wf['ct_annotated_spilterlize_integrate']['annotation'] = res_path_dea / 'pseudobulks' / f'{ct_level}__metadata.csv'
config_wf['ct_annotated_spilterlize_integrate']['result_path'] = res_path_dea 

module spilterlize_integrate:
    snakefile:
        PROJECT_ROOT / config['MrBiomics_path'] / 'spilterlize_integrate/workflow/Snakefile'
    config:
        config_wf['ct_annotated_spilterlize_integrate']

use rule * from spilterlize_integrate as spilterlize_integrate_*
```

I also thought about putting the cell type levels into on big data file, but I don't like this since
- then the same cells are repeated in the file &rarr; not conceptually clean
- I cannot split it by cell_type_level and then something else on top (e.g., primary_vs_organoid), since as far as I understand the `spilterlize_integrate` workflow doesn't support combinatorial splitting (maybe that's something that would be useful actually?)

**Comment by sreichl** [comment]
Okay, as far as I understand and how I see it: the module expects one dataset, that gets processed ie split, filtered, normalized... using the **same(!)** methods and parameters. Hence, there is no annotation file, but only a config file pointing to the `data` and `metadata`.

As I see it, your pseudobulks on different cell type annotation levels are different datasets i.e., every annotation level that downstream leads to different pseudobulk samples is a different data set. Therefore, I would configure and load the module and all subsequent/downstream modules in separate `.smk` files as they represent in my understanding spearate datasets.

Does that make sense?

**Comment by bednarsky** [comment]
- I see, for me they are just different granularities of the same dataset and I want to run the same model on all the granularities because I don't know at which one we'll find most signal. But it's an easy workaround in this case to just import the module multiple times (same thing as using different `smk` files)
- Combinatorial splitting: Agree! Had this solution in mind already but forgot it again. Maybe also worth a comment (`hint: combinatorial splitting can be achieved by dedicated columns in the annotation file`)

**Comment by sreichl** [comment]
Yes, I would still recommend separate `.smk` files and downstream modules for each dataset/granularity as this keeps the different levels nicely separate/structured not only during analyses but also on the result folder level. There is no benefit pressing it all in one result folder as integrative analyses or comparisons can be performed either way, while having readable and transparent structures. Also, some granularities might disappear and you do not want to have to touch the code for the relevant ones when you want to remove the irrelevant ones, right?
