### ISSUE TITLE
Content and use of `feature_annotation` only became clear to me when looking into the code

### ISSUE THREAD

**Issue by bednarsky** [epigen/spilterlize_integrate#17]
Hi Stephan, 

don't know if you care about these kind of issues, because one can solve them by looking into the code. But I think one shouldn't have to look into it to fill in the config files.

For example, I wouldn't have known which columns the `feature_annotation` file needs to have. 

One solution could also be that you say people have to look into the code (the code is very clear anyways) - because this is the ultimate documentation (pragmatic programmer). An approach like this would avoid duplication and might thus be nice. But then you have to clearly state somewhere that that's expected.

**Comment by sreichl** [comment]
No, this should be documented within the `config.yaml` ie at the point where it is needed.

Does this not suffice?https://github.com/epigen/spilterlize_integrate/blob/de358364821fe2cd7c2ede9efd408b16b6062798/config/config.yaml#L14-L16

If not, what exactly is missing?

**Comment by bednarsky** [comment]
- Ah sorry, now I see that it would have become clear if I read the whole config first. My fault - nothing to change really
- Maybe add a comment for confused people (like me) saying: `columns of this file defined according to parameters set below`
