### ISSUE TITLE
How to provide annotation from other rule when using as module within larger workflow?

### ISSUE THREAD

**Issue by bednarsky** [epigen/spilterlize_integrate#19]
- In my use-case, the annotation file for this workflow is a metadata file from pseudobulk generation
- I generate the pseudobulks and metadata with a snakemake workflow, i.e., they are outputs from a rule
- Then I import this workflow as module
- This workflow tries to load the annotation file to build its DAG. This fails, if the pseudobulk generation (and everything before) did not run yet since the annotation file is still missing
- What is the best way to make the module loading wait for the generation of the annotation files? Not sure [checkpoints](https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#data-dependent-conditional-execution) are the way to go, since the annotation file is loaded in the Snakefile of the module, not in a rule of the module. 
- PS: for other MrBiomics workflows the annotation file is more akin to configuration rather than metadata. Thus, there I use functions that are called in my workflow (before DAG generation) to make my whole workflow run from start to end. This does not work in this case
- PPS: I know, I could just run it until before the module, then save it from there and from this time on it will always run. Just wondering if there is a better solution

**Comment by sreichl** [comment]
Your PPS is the way to go/best practices (I will add something about "MrBiomics continuity" to the docs). As you correctly observed the annotation file is used by Snakemake (and not only as input for rules) to actually generate the DAG, hence it is required before and `checkpoints` apply only to workflow rules.
