### ISSUE TITLE
reComBat environment fails because of reComBat dependency

### ISSUE THREAD

**Issue by kvetab** [epigen/spilterlize_integrate#8]
There is a (known) issue with installing reComBat by pip, because it lists sklearn as one of its dependencies, which is unavailable since Dec 2023.
An exisiting issue here: https://github.com/BorgwardtLab/reComBat/issues/4
The underlying problem: https://github.com/scikit-learn/sklearn-pypi-package

This prevents conda from creating the reComBat environment and therefore the whole pipeline doesn't run.

**Comment by dariarom94** [comment]
Idea didn't work - tried doing it as recommended with poetry and wasn't able to build dependancies.
My local fast solution was: remove reComBat from yaml file, make the environment. Let the first round of jobs fail, activate it, and use the "last resort" solution: add environmental variable SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid the error. Make sure the variable isn't saved long-term!

**Comment by sreichl** [comment]
current plan:

- [ ] fork it into epigen
- [ ] fix the issue
- [ ] add it to the environment specification yaml like before on the aatcseq_pipeline with Bekir's MultiQC module: https://github.com/epigen/atacseq_pipeline/blob/269271ef0acb9046f6c9a67dfee47c14f136e96a/workflow/envs/multiqc.yaml#L13

**Comment by animesh3008** [comment]
Hi, I faced the same issue while installing reComBat by pip. Since we do not need it for integration for our analysis, Stephan's workaround (https://github.com/epigen/spilterlize_integrate/issues/8#issuecomment-1961789660) worked for me. 
Thanks!

**Comment by alberto-jj** [comment]
Another potential workaround, tested in Google Colab is using pip's -no-deps option as follows:

`pip install --no-deps recombat`

**Comment by sreichl** [comment]
thanks, I will have to check if I can use the flag in the environment YAML file. Below are some links for myself to check out.

- https://github.com/conda/conda/issues/6805
- https://github.com/conda/conda/issues/7911
- https://stackoverflow.com/questions/75164677/pip-install-with-no-deps-in-conda-environment-yml
- https://stackoverflow.com/questions/68584223/pip-dependencies-of-dependencies-when-installed-from-conda-environment-yaml/71469865#71469865

**Comment by sreichl** [comment]
maybe this works from [here](https://github.com/conda/conda/issues/6805#issuecomment-361782555)

```
- pip:
  - git+https://github.com/BorgwardtLab/reComBat --install-option="--no-deps"
```

**Comment by sreichl** [comment]
let's try this: https://snakemake.readthedocs.io/en/stable/snakefiles/deployment.html#providing-post-deployment-scripts

**Comment by sreichl** [comment]
installation works with post-deployment script using snakemake. still requires testing of functionality.
